name: Terraform Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_ROLE_ARN: arn:aws:iam::215502568245:role/role_for_github_actions

permissions:
  id-token: write
  contents: read

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - run: aws sts get-caller-identity
